### PR TITLE
Changed: Only re-render when text has changed

### PR DESCRIPTION
**Pull request by dail8859**
This keeps track of when text modifications that have been made. Multiple modifications can be made "at the same time" (i.e. between SCN_UPDATEUI notifications) such as when undoing or redoing. This also eliminates the need to store a previous version of the entire text.

### CODE REVIEW

**Comment by nea** [comment]
Hey there

Thanks for being so active. 

That is exactly what I was looking for (hence my commented code before) but was too lazy until now. Thanks for making the effort 👍 

I will make some very minor changes to match my personal coding style and merge it tomorrow (again, too lazy this evening ^^).


Cheers

**Comment by dail8859** [comment]
Make any changes you need!

**Comment by nea** [comment]
Hey dail8859

I made some changes regarding naming and where to check (I moved it to the Update method as I want to keep notification handling and updating separated).

And I also made a change in when to check for rendering updates, as it was not rendering e.g. the first time a document is opened, of if a document changed, while the MarkdownViewer++ was closed.

I hope all the changes are agreeable, so that I will merge the PR later.


Cheers

**Comment by dail8859** [comment]
Everything looks good to me. 👍

**Pull request merged**
